<?php
$email=$_GET["email"];
$conn=new mysqli("localhost:3306", "root", "", "chanakya");
if($conn->connect_error)
{
    die("connection failed".$conn->connect_error);
}
$s="select * from accounts where email='$email';";
$r=$conn->query($s);
if($r->num_rows)
{
//     require'PHPMailer-5.2.25/PHPMailerAutoload.php'; 
// $x=rand(100000,500000);
// $mail=new PHPMailer();
// $mail->isSMTP();
// $mail->SMTPDebug = 0;
// $mail->SMTPAuth = true;
// $mail->SMTPSecure = 'tls';
// 	$mail->Host ='smtp.gmail.com';
// 	$mail->Port = '587';
// 	$mail->isHTML(true);
// 	$mail->Username = 'chanakyagondi@gmail.com';
// 	$mail->Password = 'itzmechanakya';
// 	$mail->SetFrom('chanakyagondi@gmail.com');
// 	$mail->Subject = 'REQUEST FOR NEW PASSWORD';
// 	$mail->Body = "your new password is TNPC-'$x'";
//         $mail->AddAddress($_GET["email"]);
//  	if(!$mail->Send()) {
//    	 echo "Mailer Error: " . $mail->ErrorInfo;
// 	}



    // $SENDGRID_API_KEY='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';

    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $x=rand(100000,500000);
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://api.sendgrid.com/v3/mail/send");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"personalizations\": [{\"to\": [{\"email\": \"$email\"}]}],\"from\": {\"email\": \"tnpc@cbit.ac.in\"},\"subject\": \"Sending OTP\",\"content\": [{\"type\": \"text/plain\", \"value\": \" $x \"}]}");
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = "Authorization: Bearer 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";
$headers[] = "Content-Type: application/json";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);



if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);




	$row=$r->fetch_assoc();
        $sql="update accounts set password='$x' where email='$email'";
        $r1=$conn->query($sql);
        if(!$r1)
            echo $conn->error;
        else {
            echo "<html><script>alert('Password Changed kindly check your mail')</script></html>";
            include "index.php";
        }
}
else 
{
    echo "<html><script>alert('Not registered with this mail,kindly register ')</script></html>";
    include "forgotpassword.php";
}
    $conn->close();


?>